### PR TITLE
Allow exposed ports to be added to container

### PR DESCRIPTION
**Pull request by kevinherron**

### CODE REVIEW

**Comment by benmusson** [comment]
What does this gain us besides the `checkNotRunning` validation?

Can't we already call `addExposedPort` before starting the container?

**Comment by kevinherron** [comment]
Yeah this is probably unnecessary. When I started trying to figure out how to expose additional ports I didn’t realize it was just a call to the superclass. Never stopped to think about it further 😅

**Comment by benmusson** [comment]
Closing.

**Comment by benmusson** [comment]
> Went back to just use `addExposedPort` and realized it returns `void` and doesn't chain nicely. Cosmetic, but still something.

Looks like the intended chain-able method is `withExposedPorts`.
https://java.testcontainers.org/features/networking/

```java
IgnitionContainer ignition = new IgnitionContainer("inductiveautomation/ignition:8.1.33")
    .withExposedPorts(500)
    .withExposedPorts(501)
    .start()
```

**Comment by kevinherron** [comment]
> > Went back to just use `addExposedPort` and realized it returns `void` and doesn't chain nicely. Cosmetic, but still something.
> 
> Looks like the intended chain-able method is `withExposedPorts`. https://java.testcontainers.org/features/networking/
> 
> ```java
> IgnitionContainer ignition = new IgnitionContainer("inductiveautomation/ignition:8.1.33")
>     .withExposedPorts(500)
>     .withExposedPorts(501)
>     .start()
> ```

It looks to me like `withExposedPorts` calls `setExposedPorts`, which clears all previously set ports. I think its intention is you provide _all_ ports you want exposed in a single call.

**Comment by benmusson** [comment]
```java
public void setExposedPorts(List<Integer> exposedPorts) {
    this.containerDef.exposedPorts.clear();
    ....
}
```

Ah gotcha, I'm following now.

**Comment by benmusson** [comment]
> Had I seen any of this I probably would have named my method `withAdditionalExposedPort`.

It looks like the .NET version of testcontainers has a `.withExposedPort` method that does exactly what you've proposed, but yeah, I'm concerned about adding something named too close to the Java default `.withExposedPorts` that behaves differently.

I like `withAdditionalExposedPort`.

**Pull request merged**
